{
    "name": "AI Task Assistant — Business",
    "version": "17.0.1.0.0",
    "summary": "500 tasks/month — for growing teams",
    "description": "See static/description/index.html",
    "category": "Project",
    "author": "Alan Marquez",
    "website": "https://www.lokeai.es",
    "license": "OPL-1",
    "depends": ["ai_task_assistant"],
    "data": [],
    "images": ["static/description/icon.png", "static/description/banner.png"],
    "installable": True,
    "application": False,
    "auto_install": False,
    "price": 199,
    "currency": "EUR",
    "support": "soporte@lokeai.es",
}
