import logging
from contextlib import closing

import requests

from odoo import api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

# Production backend URL (hardcoded)
AI_BACKEND_URL = "https://odoo.lokeai.es"


class ProjectTask(models.Model):
    _inherit = "project.task"

    x_ai_summary = fields.Html(
        string="AI Summary",
        readonly=True,
        help="Automatically generated by AI when the task is assigned.",
    )
    x_ai_status = fields.Selection(
        selection=[
            ("pending", "Pending"),
            ("processing", "Processing"),
            ("done", "Done"),
            ("error", "Error"),
        ],
        string="AI Status",
        default="pending",
        readonly=True,
    )

    def _compute_has_subtasks(self):
        for task in self:
            task.x_has_subtasks = bool(task.child_ids)

    x_has_subtasks = fields.Boolean(
        string="Has subtasks",
        compute="_compute_has_subtasks",
        help="True when the task has child subtasks.",
    )
    x_ai_subtasks_generated = fields.Boolean(
        string="AI subtasks generated",
        default=False,
        help="True when subtasks were created by AI. Used to show Regenerate vs Generate.",
    )
    x_ai_generated = fields.Boolean(
        string="AI generated",
        default=False,
        help="True when this subtask was created by AI. Used to avoid deleting manual subtasks on regenerate.",
    )
    x_ai_license_ok = fields.Boolean(
        string="AI license OK",
        compute="_compute_x_ai_license_ok",
        help="True when license is active (API key set and within limit).",
    )
    x_ai_subtask_instructions = fields.Text(
        string="AI Instructions",
        help="Optional instructions for AI when generating or regenerating sub-tasks (e.g. 'Focus on testing', 'Include deployment steps').",
    )

    def _compute_x_ai_license_ok(self):
        icp = self.env["ir.config_parameter"].sudo()
        for task in self:
            api_key = (icp.get_param("ai_task_assistant.api_key", "") or "").strip()
            if not api_key:
                task.x_ai_license_ok = False
                continue
            limit = int(icp.get_param("ai_task_assistant.license_tasks_limit", 0) or 0)
            used = int(icp.get_param("ai_task_assistant.license_tasks_used", 0) or 0)
            task.x_ai_license_ok = limit == 0 or used < limit

    def _ai_get_param(self, key):
        return self.env["ir.config_parameter"].sudo().get_param(key, "")

    def write(self, vals):
        # Backend is called ONLY from the manual "Generate sub-tasks with AI" button.
        # No automatic trigger on assignment (automation rule was removed).
        return super().write(vals)

    def action_trigger_ai_analysis(self):
        for task in self:
            if task.x_ai_status == "processing":
                raise UserError("AI analysis is already in progress. Please wait.")
            task._send_to_ai_backend(sync=True)
        # Reload the form to show the new summary and subtasks
        return {
            "type": "ir.actions.act_window",
            "res_model": "project.task",
            "res_id": self.id,
            "view_mode": "form",
            "target": "current",
        }

    def _send_to_ai_backend(self, sync=False):
        api_key = self._ai_get_param("ai_task_assistant.api_key")
        if not api_key:
            _logger.warning("AI Task Assistant: API key not configured. Activate your license first.")
            return

        manual_subtasks = [c.name for c in self.child_ids if not c.x_ai_generated and (c.name or "").strip()]
        payload = {
            "task_id": self.id,
            "name": self.name,
            "description": self.description or "",
            "user_ids": self.user_ids.ids,
            "project_id": self.project_id.id,
            "project_name": self.project_id.name or "",
            "existing_subtasks": manual_subtasks,
            "instructions": (self.x_ai_subtask_instructions or "").strip() or "",
            "odoo_url": (self._ai_get_param("ai_task_assistant.odoo_callback_url") or "").strip().rstrip("/") or self._ai_get_param("web.base.url"),
            "odoo_db": self.env.cr.dbname,
            "odoo_callback_login": self._ai_get_param("ai_task_assistant.odoo_callback_login"),
            "odoo_callback_api_key": self._ai_get_param("ai_task_assistant.odoo_callback_api_key"),
            "llm_provider": self._ai_get_param("ai_task_assistant.llm_provider") or "ollama",
            "llm_api_key": self._ai_get_param("ai_task_assistant.llm_api_key") or "",
            "force": self.x_ai_subtasks_generated,
        }
        headers = {
            "X-API-Key": api_key,
            "Content-Type": "application/json",
        }

        try:
            if sync:
                # Use a separate cursor/connection so we don't hold a lock on the task row.
                # The backend callback (or form auto-save) can then update without
                # SERIALIZATION_FAILURE (concurrent update).
                try:
                    with closing(self.env.registry._db.cursor()) as new_cr:
                        new_env = api.Environment(new_cr, self.env.uid, self.env.context)
                        new_env["project.task"].browse(self.id).sudo().write(
                            {"x_ai_status": "processing"}
                        )
                        new_cr.commit()
                except Exception as e:
                    _logger.warning(
                        "AI Task Assistant: Separate cursor for processing status failed (%s), "
                        "falling back to main transaction",
                        e,
                    )
                    self.sudo().write({"x_ai_status": "processing"})
                    self.env.cr.commit()
            else:
                self.sudo().write({"x_ai_status": "processing"})
            timeout = 60 if sync else 5
            resp = requests.post(
                f"{AI_BACKEND_URL.rstrip('/')}/task-assigned",
                json=payload,
                headers=headers,
                params={"sync": "1"} if sync else None,
                timeout=timeout,
            )
            if resp.status_code not in (200, 202):
                _logger.error("AI Task Assistant – backend returned %s: %s", resp.status_code, resp.text[:200])
                self.sudo().write({"x_ai_status": "error"})
                if sync:
                    try:
                        err = resp.json()
                        detail = err.get("detail", resp.text[:300])
                        if resp.status_code == 429 and isinstance(detail, dict) and detail.get("code") == "limit_reached":
                            # Call sync license to refresh license data (tier, used, limit, reset_date)
                            synced = self.env["res.config.settings"]._sync_license_from_backend(api_key)
                            if not synced:
                                # Fallback: update from 429 response (no reset_date)
                                icp = self.env["ir.config_parameter"].sudo()
                                icp.set_param("ai_task_assistant.license_tier", detail.get("tier", ""))
                                icp.set_param("ai_task_assistant.license_tasks_used", str(detail.get("tasks_used", 0)))
                                icp.set_param("ai_task_assistant.license_tasks_limit", str(detail.get("tasks_limit", 0)))
                            msg = detail.get("message", str(detail))
                        elif isinstance(detail, dict):
                            msg = detail.get("message", str(detail))
                        else:
                            msg = detail if isinstance(detail, str) else str(detail)
                    except Exception:
                        msg = resp.text[:300] or f"Backend returned {resp.status_code}"
                    raise UserError(msg)
        except requests.exceptions.Timeout:
            _logger.error("AI Task Assistant – webhook timeout")
            self.sudo().write({"x_ai_status": "error"})
            if sync:
                raise UserError("The request timed out. Please try again.") from None
        except requests.exceptions.RequestException as exc:
            _logger.error("AI Task Assistant – webhook error: %s", exc)
            self.sudo().write({"x_ai_status": "error"})
            if sync:
                raise UserError(str(exc)) from exc
        except UserError:
            raise
        except Exception as exc:
            _logger.error("AI Task Assistant – webhook error: %s", exc)
            self.sudo().write({"x_ai_status": "error"})
            if sync:
                raise UserError(str(exc)) from exc
